// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpofjtainrndcvixqusq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwb2ZqdGFpbnJuZGN2aXhxdXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzIxOTksImV4cCI6MjA3MjU0ODE5OX0.U_029pWWA13w3zipV2HLIr32k24_6cd59vN9Je4mjl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});